apiVersion: v1
kind: Service
metadata:
  name: {{ include "gaussian-backend-demo.fullname" . }}
  labels:
    {{- include "gaussian-backend-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "gaussian-backend-demo.selectorLabels" . | nindent 4 }}
